### ISSUE TITLE
请问支持whisper模型没

### ISSUE THREAD

**Issue by nokiy** [BurnHair/issues#1]
当前分组 default 下对于模型 whisper-1 无可用渠道 （request id：
20240315060924241563543ptiRYddl）

我调用的话就是报错这个

调用接口的话，我是拼接的 ： https://burn.hair/v1/audio/transcriptions

**Comment by roberchen820** [comment]
url = 'https://burn.hair/v1/chat/completions' #https://burn.hair/
        headers = {
            'Authorization': 'Bearer sk-xxx'
        }
        # 要发送的数据
        data = {
            "model": "gpt-3.5-turbo",
            "messages": [
                {
                  "role": "user",
                  "content": "test"
                }
            ],
            "temperature": 0.7
        }
        response = requests.post(url, headers=headers, data=data) # 发起POST请求
返回503

**Comment by nokiy** [comment]
多谢大佬！





------------------ 原始邮件 ------------------
发件人: roberchen820 ***@***.***&gt;
发送时间: 2024年3月15日 19:26
收件人: BurnHair/issues ***@***.***&gt;
抄送: nokiy ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [BurnHair/issues] 请问支持whisper模型没 (Issue #1)





     url = 'https://burn.hair/v1/chat/completions' #https://burn.hair/     headers = {         'Authorization': 'Bearer sk-xxx'     }     # 要发送的数据     data = {         "model": "gpt-3.5-turbo",         "messages": [             {               "role": "user",               "content": "test"             }         ],         "temperature": 0.7     }     response = requests.post(url, headers=headers, data=data) # 发起POST请求  
返回503

**Comment by BennyThink** [comment]
坏了，在修.jpg

**Comment by BennyThink** [comment]
好了好了，再试试看

**Comment by nokiy** [comment]
搞定，多谢🙏
https://burn.hair/v1/chat/completions






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BurnHair/issues"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月16日(星期六) 晚上10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BurnHair/issues] 请问支持whisper模型没 (Issue #1)





 
好了好了，再试试看
