### ISSUE TITLE
为什么使用gpt-4-0125-preview对话，消费记录却有gpt-3.5-turbo

### ISSUE THREAD

**Issue by myunco** [BurnHair/issues#2]
![1](https://github.com/BurnHair/issues/assets/26001944/d2f69914-b740-491b-ae0f-2508fc2e6359)
![2](https://github.com/BurnHair/issues/assets/26001944/1832c1d6-cc18-40f0-8fdb-c338bccf519e)

**Comment by Kzh110** [comment]
因为标题是3.5生成的
