### ISSUE TITLE
A newly registered GitHub account

### ISSUE THREAD

**Issue by Jeff-apple1918** [BurnHair/issues#21]
From Geek:
A newly registered GitHub account displays as ineligible for registration. As a newcomer using it for the first time, I hope to get on board. Thank you, experts!

**Comment by BennyThink** [comment]
You're in the whitelist now. Wait for 10 minutes and try again.

**Comment by Jeff-apple1918** [comment]
After testing, it still doesn't work.

**Comment by BennyThink** [comment]
try to close your browser and try again. Better include a screenshot or video

**Comment by Jeff-apple1918** [comment]
![Uploading PIC1.png…]()

**Comment by Jeff-apple1918** [comment]
错误：您不符合注册条件，请联系站长处理。

**Comment by davidweb369** [comment]
I have the same problem! Please help! Thank you!

**Comment by BennyThink** [comment]
all added, please try again

**Comment by BennyThink** [comment]
it's a bug, I just fixed it.

**Comment by vanmiao** [comment]
新注册的 GitHub 帐户显示不符合注册资格。我希望能够加入。谢谢各位大神！

**Comment by Krammmer765** [comment]
你好，github登录提示不符合注册条件，请问怎么解决呢?
