### ISSUE TITLE
BUG: 在LobeChat中刚问了一个字，回复这个

### ISSUE THREAD

**Issue by devyujie** [BurnHair/issues#22]
![image](https://github.com/BurnHair/issues/assets/48620527/899cd63e-86dd-41b9-b9f2-0dbe12013a21)

**Comment by devyujie** [comment]
3.5turbo 不都默认指向0125 16k模型了吗，哪来的4k...

**Comment by BennyThink** [comment]
可能是我配置错了，你用 `gpt-3.5-turbo-0125` 看看
