### ISSUE TITLE
正常使用账号无法登录

### ISSUE THREAD

**Issue by finalkira000** [BurnHair/issues#24]
Hi 我的github 账号登录无法访问了麻烦解决一下

**Comment by BennyThink** [comment]
没有看到你的账号有任何异常啊。有截图吗

**Comment by finalkira000** [comment]
![image](https://github.com/BurnHair/issues/assets/13897489/73212bfe-d8ed-4b81-bf73-de58a39a00bc)

**Comment by finalkira000** [comment]
解决了，多谢
