### ISSUE TITLE
似乎不能用TTS模型

### ISSUE THREAD

**Issue by yensen2006** [BurnHair/issues#28]
似乎不能用TTS模型，请问有解决的办法吗？

**Comment by BennyThink** [comment]
支持的。
<img width="842" alt="image" src="https://github.com/BurnHair/issues/assets/14024832/bba31e93-822a-4b5f-9440-9e223a83101e">

接口 `https://burn.hair/v1/audio/speech`

```json
{
    "model": "tts-1",
    "input": "Today is a wonderful day to build something people love!",
    "voice": "alloy"
}
```
