### ISSUE TITLE
lobechat里使用api为啥出的是空白

### ISSUE THREAD

**Issue by kokkiooo** [BurnHair/issues#39]

**Comment by kokkiooo** [comment]
lobechat里调用api是空白呢

**Comment by BennyThink** [comment]
可能你配置的不正确？我刚刚试了可以用的。

<img width="814" alt="image" src="https://github.com/BurnHair/issues/assets/14024832/40bf08b8-ac08-477c-83da-56fad698f6d2">

你按照如图所示配置一下看看
<img width="1137" alt="image" src="https://github.com/BurnHair/issues/assets/14024832/7566acdb-3cb7-4379-b1c9-d7441837ac3d">

**Comment by kokkiooo** [comment]
感谢解答，按照你的设置成功使用了
