### ISSUE TITLE
TTS, DALL·E等模型用不了，且有API错误

### ISSUE THREAD

**Issue by amchii** [BurnHair/issues#40]
**tts-1-hd**:
![image](https://github.com/BurnHair/issues/assets/26922464/2b02838e-b376-40b3-b2d9-399412832dad)
**dall·e**:
![image](https://github.com/BurnHair/issues/assets/26922464/e78240dd-4cec-4596-9dde-beba7639a5c7)

更奇怪的是使用`v1/audio/speech`接口传`dall·e`的生成图片接口(`v1/images/create`)参数能够成功（编辑图片(`v1/images/edit`)的失败）：
![image](https://github.com/BurnHair/issues/assets/26922464/73b40d7d-1347-41ef-a3d6-bb675d40cb06)

**Comment by BennyThink** [comment]
TTS的那个直接试试TTS看看？

其他的几个问题 我得晚上有空才能看看，可能是代码bug

**Comment by BennyThink** [comment]
应该叫 tts-1 等我晚上回去看看吧

**Comment by BennyThink** [comment]
<img width="822" alt="image" src="https://github.com/BurnHair/issues/assets/14024832/26bc0770-eff7-420e-9515-45ae2ead5f40">

好了，文档  https://burn.hair/faq
