### ISSUE TITLE
whisper-1有乱码

### ISSUE THREAD

**Issue by GH3a** [BurnHair/issues#50]
都是初中生和高��生
不少钱去买 但���今天看来有一些鸡肋
去年我花了12200 购���个人养老金

个另的字或者词是这个乱码

**Comment by BennyThink** [comment]
可以把音频文件分享出来吗？

**Comment by GH3a** [comment]
[2024-04-01 14.47.20-视频-槽叔-完整版视频，请洽经纪人获取 #保险.mp3.zip](https://github.com/BurnHair/issues/files/15033406/2024-04-01.14.47.20-.-.-.mp3.zip)

___
Completed 2024-04-01 14.47.20-视频-槽叔-完整版视频，请洽经纪人获取 #保险.mp3. 
各位團隊小夥伴們大家好 今天的例會我和大家過一下 仁寶和國壽剛剛發佈的2023年的財報 年度報告 我過的是摘要 我做保險11年了 我每年都有個習慣 就是把國壽和仁寶這兩個公司的財報 花一天的時間看一遍 每年看 然後每年六七逆 廢話不多說 我已經把兩家公司的 一個是仁寶的人民保險 2023年的年度摘要下好了 以及國壽的2023年年度報告摘要下好了 我們先看國壽 然後公司基本情況 這裡面其實要和大家講一個細節 有一個最重要的區別是什麼 國壽的上市公司指的是國壽的壽險 中國人壽保險股份有限公司 這是它的全稱 它指的是壽險這個公司 因為國壽是個大概念 它下面還有財險 養老險 資產管理公司 健康服務管理公司 包括做另類投資的投資公司 很多 可能加上其他的三級子單位就更多了 但是它針對的上市指的是 中國人壽保險股份有限公司 也就是壽險 但是仁寶就不是 仁寶針對的是什麼呢 我們看這裡面有介紹 很明顯這裡公司簡介裡面 有這樣一行字 在H股 它的名稱叫中國人民保險集團 這個集團就很重要 也就是說 仁寶的財報它針對的上市主體 是整個大集團 它包含了壽險、財險、養老險 以及健康險資產管理公司 所以大家請注意 這兩個公司都是上市公司 但是它的主體是不一樣的 一定要搞懂 我們接下來繼續看 國壽的年度報告摘要 我們跟著國壽的年度報告摘要往前走 我們看這裡公司簡介 本公司是中國領先的人壽保險公司 沒錯吧 它只是人壽保險公司 擁有由營銷員、團線銷售人員 以及專業監業代理機構組成的銷售網絡 銷售網絡非常重要 壽險公司第一重要的就是賣這個詞 賣這個字 它怎麼賣的 提供什麼呢 然後是產品 個人人壽保險 團體人壽保險 意外險、健康險等產品 也是最大的投資機構之一 也是最大的機構投資者之一 並通過控股國壽的資產管理有限公司 成為中國最大的保險資產管理公司 本公司亦控股國壽的養老保險股份有限公司 這裡提到的國壽資產、國壽養老 也是為了在年報裡面涉及到的 和子公司之間的 嚴格來講不叫子公司 是集團下轄的兄弟公司之間的一些業務關聯 提前提供一個背景 意思就是說我們和它是有關係的 所以後續產生一些業務合作 和業務交互是有邏輯可循的 所以這裡面有一個前置的這麼一個介紹 接下來我們來看一下業務數據指標 近三年的業務數據指標 這裡面是很乾貨的 全年的業績 它拿出了23年、22年和21年、3年的數據 這裡我們重點關注一個營業利潤 營業利潤很有意思 我們看23年營業利潤已經變成了122個億 122個億 去年多少呢 去年是243個億 如果再往前看看 2021年就是508億 相較於2022年又是翻倍 大家可以發現 國壽的壽險業務在過去三年 21、22、23經歷了一個什麼樣的利潤變化 壽險行業在過去幾年經歷了一個多麼tough 多麼嚴峻的一個挑戰 國壽是這樣的 那仁寶是什麼樣的呢 再次提醒大家注意 國壽的數據指的只是壽險公司 仁寶的數據包含了集團���有的售財、養老、投資 包括健康險 我們來看一看仁寶的數據怎麼樣 經濟論在這裡 我們畫一下 經濟論在這一行 可以發現2023年的經濟論 集團經濟論大概是314個億 和2022年354個億相比 是小幅下降了大概11個點左右 11個點左右 但是相較於21年還是有所增長的 但是大家看一下 從21年、22年到23年 這三個數字都維持在300到350個億之間 整體還是比較穩定的 說明仁寶財的這個利潤相對來講 沒有大幅的波動 這裡其實主要也是由於 仁寶集團的主要收入是來自於財險業務 財險業務受到過去幾年的 宏觀利率的下調 以及長期投資減值的這些風險 相對都比較小 甚至不受影響 所以得益於這一點的話 我們看到仁寶集團的利潤還是比較穩固的 其實財險這幾年日子慢慢的在好轉 因為財險已經經過了5年前 10年前開始的車改 車險廢改的振動期已經緩過來了 所以整體業務非常穩定 而且財險有一點非常重要的細節 我在這裡給大家找一找看能不能找到 就是它的綜合成本率 我們看看仁寶集團有沒有提過綜合成本率這個詞 應該是有的 應該是有的 未找到結果 在這裡 看這裡我給大家寫出來 劃比仁寶財險綜合成本率97.6% 96.7% 這是什麼意思呢 就是我收100塊錢的財險保費進來 我理賠運營服務各項成本加起來只有97.6 也就是說2.4是我凈賺的 大家能理解嗎 財險這個業務很神奇 因為它是一年期的 比如汽車 醫療險 意外險 很多是財產險公司可以做的 它今年收下來的保費到了滿一年 也就是滿365天之後 我就能知道這個業務是賺的還是虧的 它不像壽險 長期重疾險 甚至終身的壽險 你不知道今年這副樣子和明年那副樣子以後怎麼樣 不知道 所以你沒法利潤立刻兌現 或者虧損立刻填補 對吧 但財險就不是 我100塊錢收上來 成本97.6 我還留了2.4 這就叫承保利潤 大家想想很可怕 承保利潤的意思是我還沒做投資呢 我還沒去做投資呢 我都已經直接賺錢了 所以財險業務 如果經營得當的話 它即使不考慮投資方面的收益 它的經營方面的收益也是比較穩健的 有人說這個2.4個點很小 盤子很大 如果一年的這個財險保費可能三四千個億算了 一個點 一個點 綜合成本率收一個點的話就是30個億 那如果這個將近三個點的話 其實就是八九十億 事實上的人保財險 我記得在這個年報裡也說了 它的人保財險的整體的利潤 就是在100億左右 這裡面包含了以這個綜合成本率帶來的 這個費差為收益大頭的和一些投資收益 所以這裡面就比較重要 那我們來看國壽 這裡面接下來提到的是報告期內季度 四個季度的保費利息和收入 你會明顯發現 壽險公司或者說以國壽為代表的壽險公司 它的保費收入是從一季度開始達到一個峰值 然後二三四季度逐步遞減 它的業務節奏就是開年很火 是不是開門紅 對吧 開門紅 所以它一年收的保費就能占將近70%左右 一年是5000億左右 對吧5000億左右 那它第一個季度就能夠大概占65%到70% 接下來是股本及股東情況 一個是國壽股份 一個是人保集團 這裡面股東情況線上就凸顯了 這兩個主體不同 帶來的區別 我們這麼看 現在你看到的頁面是國壽股份 它的股東很簡單 有這麼幾個 第一個是集團 對吧集團是它的老板 是它的股東 集團大概占68.37% 除此之外由於在香港上市的 所以境外法人股大概是四分之一的樣子 那我們回到人保那邊 我們看一看人保的數據是什麼樣子 我們發現人保集團的第一名股東是財政部 財政部持股是60.84% 基本上就是60 那你會發現為什麼人保有財政部持股 但是國壽就沒有財政部持股呢 其實不是這樣的 我們看人保財政部持股 是因為這是個集團的股權 對不對 集團再往上走就直接是財政部控股了 但是��到那句話 國壽現在我們看到的是國壽股份 再往上是沒有財政部的 是要通過集團來控股 集團的大股東就是財政部 很簡單 那集團的股東是財政部的話 大概占比多少呢 在他們的官網上也有詳細的介紹 比如說我們來到這裏 公司這裏幹要 這裏面也有詳細的說明 你看這句話 中國人壽集團是大型控股公司 實際控制為中華人民共和國財政部 中華人民共和國財政部持有國壽集團90股權 也就是說財政部持有90集團的股權 然後集團又持有68% 大概70%的壽險股權 然後用90%乘以70% 大概是62% 也就是說財政部持有的國壽股份 我們進行打穿 就知道財政部持有國壽股份62% 大約60%左右的股份了 那這一點看是不是��人保集團一樣呢 沒錯 人保集團數據又一樣了 但實際上這個一樣沒什麽意義 但這裏其實是不一樣的 就是人保集團的財政部占比只有60% 但是國壽集團的財政部占比是90% 這裏的差別就是因為人保集團是上市主體 所以它將更多的股份均勻的給到了市場 給到了港股和A股 給到了H股和A股 相當於人保集團財政部控股60% 但是國壽集團財政部就控股90%了 這個控股權差別還是比較大的 但有一點很有意思 在這裏也說一下 不管是誰 不管哪家公司 它都將10%的集團公司的股權 劃給了全國社保基金理事會 這裏是國壽的 然後這裏是人保集團的 社保基金理事會持有了人保集團12.68%的股權 所以這方面我在書裏也說過 央企要將股權的10%劃轉到社保基金理事會 讓社保基金理事會去享有股權的投資和收益 那我們繼續看國壽的年報的摘要 接下來是非常有意思的重要事項 重要事項是很重要在哪呢 為什麽叫重要事項
___
上面为结果

**Comment by BennyThink** [comment]
修好了

**Comment by GH3a** [comment]
仍然有问题
有些音频并没有识别

而直接出来的结果是
{"text":"请不吝点赞 订阅 转发 打赏支持明镜与点点栏目"}

很多这个结果！

**Comment by GH3a** [comment]
> 修好了

{"text":"请不吝点赞 订阅 转发 打赏支持明镜与点点栏目"}

是否使用了别人的插件
