### ISSUE TITLE
新注册的账号无法登录

### ISSUE THREAD

**Issue by lianghshaohouqi** [BurnHair/issues#55]
账号名称是：liangshaohouqi   无法登录，提示错误：您不符合注册条件，请联系站长！重新注册了一个邮箱重新登录还是不行哦 
![9c91fb60a6cb61aa273f70474b6268e](https://github.com/BurnHair/issues/assets/167315411/7fced592-c838-4844-a909-7bd1c1005987)

**Comment by lianghshaohouqi** [comment]
还是登录不了哦！还是弹出错误提示：您不符合注册条件

**Comment by BennyThink** [comment]
你确定是这个账号吗 https://github.com/lianghshaohouqi 

再试一次看看，已经加进去了

**Comment by lianghshaohouqi** [comment]
不好意思，是这个账号：lianghshaohouqi   麻烦帮添加下哦  谢谢啦

**Comment by BennyThink** [comment]
这和那个有什么区别，你再试试看。

**Comment by lianghshaohouqi** [comment]
原来的中间少了一个h

**Comment by lianghshaohouqi** [comment]
原来的中间少了一个h

**Comment by BennyThink** [comment]
总之你再试试吧，我原样粘贴进去了

**Comment by lianghshaohouqi** [comment]
![1713452313961](https://github.com/BurnHair/issues/assets/167315411/5596b415-571f-44ff-8b49-1423e9df6cd1)

**Comment by BennyThink** [comment]
我们名单里添加的就是这个 lianghshaohouqi

如果还不能那你要检查下是不是选择了正确的账号
