### ISSUE TITLE
whisper有问题

### ISSUE THREAD

**Issue by GH3a** [BurnHair/issues#59]
{"text":"请不吝点赞 订阅 转发 打赏支持明镜与点点栏目"}

会识别为这个信息

**Comment by BennyThink** [comment]
🤔什么意思

**Comment by BennyThink** [comment]
https://github.com/BurnHair/issues/issues/50

原来你把评论加到了这里。

没有用插件，只是单纯的替换了那个字符

**Comment by GH3a** [comment]
> 🤔什么意思

识别的时候，不论mp3的内容是什么，都会出现这个结果，也就是放弃了识别，直接输出上面那个广告。

**Comment by BennyThink** [comment]
这不对劲啊，我随便找了个音频没问题啊 你的音频文件有吗

**Comment by GH3a** [comment]
> 这不对劲啊，我随便找了个音频没问题啊 你的音频文件有吗

我一共识别了100多个，里面出现了3个这个。但是如果用那3个文件单独再识别一次，就不会再出现了。是随时的。
应该是模型里做了手脚。

**Comment by BennyThink** [comment]
啊我搜了一下

* https://twitter.com/mave99a/status/1717052743490420903?lang=zh
* https://github.com/openai/whisper/discussions/2015
* https://cn.v2ex.com/t/993171
* https://twitter.com/vista8/status/1729801808564875414


看起来这是 OpenAI的模型有问题😂

**Comment by GH3a** [comment]
> * https://twitter.com/mave99a/status/1717052743490420903?lang=zh

是有人污染了模型，故意投毒吧。哈哈

**Comment by BennyThink** [comment]
我猜也是，被投毒了😂

**Comment by GH3a** [comment]
> * https://cn.v2ex.com/t/993171

去搜索了明镜和点点，是些FG的频道，FLG的

**Comment by BennyThink** [comment]
😂 这得找 openai说理去，不过whisper是开源的

**Comment by GH3a** [comment]
> {"text":"请不吝点赞 订阅 转发 打赏支持明镜与点点栏目"}



> 😂 这得找 openai说理去，不过whisper是开源的

你可以在api接口，加一个判断，如果等于这个，再重新做一次，再return，可以吗？

**Comment by GH3a** [comment]
> 有道理，不过这里涉及到计费相关的，总不能扣两次费用。可能得多花点时间

花第二次时间是可以接受的，总比，发现了再手动再来一次好吧。

**Comment by BennyThink** [comment]
等我今晚改改，问题不大

**Comment by GH3a** [comment]
> 等我今晚改改，问题不大 。可能有个问题，假如有的人音频文本就是这个，那么就循环了😂 特殊处理下应该可以

while true第2次就可以放行了，2次都这个，就返回这个了

**Comment by BennyThink** [comment]
> > 等我今晚改改，问题不大 。可能有个问题，假如有的人音频文本就是这个，那么就循环了😂 特殊处理下应该可以
> 
> 
> 
> while true第2次就可以放行了，2次都这个，就返回这个了

嗯 我也是这么想的😎

**Comment by BennyThink** [comment]
应该修好了 ，判断了如果包含`打赏支持明镜与点点栏目`那就再请求一次，你再试试看

**Comment by 15730654943** [comment]
怎么上下文呢，请求的是同一个对话
