### ISSUE TITLE
gpt-4-1106-preview模型请求异常

### ISSUE THREAD

**Issue by tnwxagns** [BurnHair/issues#6]
错误了非常之高，错一次回答一次，下次继续报错{

  "error": {

    "message": " (request id: 20240327135033775021121Pbf32J5o)",

    "type": "upstream_error",

    "param": "530",

    "code": "bad_response_status_code"

  }

}

**Comment by BennyThink** [comment]
啥情况，我试了一下没事啊

 
<img width="600" alt="image" src="https://github.com/BurnHair/issues/assets/14024832/e8cafda1-9fb3-445d-9b33-66b366d98214">

**Comment by BennyThink** [comment]
好的，DNS配置的有点问题，马上修

**Comment by BennyThink** [comment]
应该好了:-)

**Comment by tnwxagns** [comment]
没啥问题啦
