### ISSUE TITLE
请问是否支持：text-embedding-3-large

### ISSUE THREAD

**Issue by tianzhuwei** [BurnHair/issues#61]
你好，如题目所问，是否支持 text-embedding-3-large 这类embedding类的模型呢

**Comment by BennyThink** [comment]
当然支持，三个模型都可以。

https://github.com/BurnHair/issues/blob/master/doc.md#16-embeddings

**Comment by tianzhuwei** [comment]
> 当然支持，三个模型都可以。
> 
> https://github.com/BurnHair/issues/blob/master/doc.md#16-embeddings

got it
