### ISSUE TITLE
我需要填进某浏览器扩展里，但是连接失败，或许是Url的问题？？

### ISSUE THREAD

**Issue by Sunsh4j** [BurnHair/issues#66]
![image](https://github.com/BurnHair/issues/assets/43169575/b9e485cf-e18c-440b-a2ee-fe402eff3266)

试了使用文档里的不少url，但是都不行，请教下，我该填入什么呢？

**Comment by BennyThink** [comment]
试试 https://burn.hair/ 或者 https://burn.hair/v1

**Comment by BennyThink** [comment]
你的这个扩展叫什么名字，我来试试看

**Comment by BennyThink** [comment]
<img width="632" alt="image" src="https://github.com/BurnHair/issues/assets/14024832/4a14a214-b464-46cd-8a01-c8cd75b31d3e">

这样填写，看到请求日志了

<img width="947" alt="image" src="https://github.com/BurnHair/issues/assets/14024832/1ca1739a-1ada-4df6-b628-455b5c938efc">

**Comment by BennyThink** [comment]
奇怪了呀 我也是和你一模一样的配置。试试重新生成一个令牌呢？

**Comment by BennyThink** [comment]
https://github.com/BurnHair/issues/assets/14024832/c368d9f9-7e45-4101-b278-de7f5a8fac9f

你看看，没问题呀，能打开F12 看有没有什么 log 之类的吗？

**Comment by BennyThink** [comment]
可能不太行🫠 这个问题确实很奇怪，试试全局VPN之类的？

**Comment by BennyThink** [comment]
这真的很奇怪，给他们反馈个问题试试？是不是要登录个他们的账号？

**Comment by BennyThink** [comment]
这就太奇怪了，你看我录制的视频里，我可以用啊🫠  

你能用 postman之类的，根据文档，试试？ https://github.com/BurnHair/issues/blob/master/doc.md#11-chat-competions

**Comment by BennyThink** [comment]
用 lobechat的话，接口代理地址要写 https://burn.hair/v1

**Comment by BennyThink** [comment]
未解之谜了🥲 所以你的网络应该没问题的 🥲 毫无头绪了

**Comment by BennyThink** [comment]
哦豁厉害，你能把他的那个报错截图发给我吗，这样我更能了解原因？

**Comment by BennyThink** [comment]
修了一下，你试试看？

**Comment by BennyThink** [comment]
可能是4比较慢，或者有失败的。我还没有监测4的状态，不知道成功率如何

**Comment by BennyThink** [comment]
等我有空可能需要监测下4的稳定性，现在只有3.5的监测

**Comment by BennyThink** [comment]
> 再反馈一下，官网的页面有时会打不开🤣🤣

不太可能吧🥲可能是因为有 Cloudflare ？

**Comment by BennyThink** [comment]
这个页面可能忘了做检查了，应该要先登录
