### ISSUE TITLE
whisper 会支持 `timestamp_granularities[]` 参数吗

### ISSUE THREAD

**Issue by xinnay** [BurnHair/issues#68]
目前 `/v1/audio/transcriptions` 只支持 `model` 和 `file` 参数，后续考虑支持其他参数吗？

**Comment by BennyThink** [comment]
当然会:-) word 和segment都支持

<img width="999" alt="image" src="https://github.com/BurnHair/issues/assets/14024832/65c0f8ce-7f62-4fab-9bac-f42188d0dc36">
