### ISSUE TITLE
如何在沉浸式翻译里使用？

### ISSUE THREAD

**Issue by yibie** [BurnHair/issues#70]
网络无法访问。

**Comment by BennyThink** [comment]
* 需要填入 API Key和代理地址，根据不同的软件，代理地址可能是 `https://burn.hair` 或 `https://burn.hair/v1`。
* 网络无法访问，有截图吗？

**Comment by yibie** [comment]
返回错误消息：
404: {"error":{"message":"Invalid URL (POST /v1/models)","type":"invalid_request_error","param":"","code":""}}
我后台的设置：
<img width="782" alt="image" src="https://github.com/BurnHair/issues/assets/365484/3ca982e9-5dcb-4f8f-ad5b-309a15ee8411">

**Comment by BennyThink** [comment]
你的自定义API接口地址可能不正确，参考下他的说明配置下。

**Comment by yibie** [comment]
你好，我没看懂它的接口地址说明，按照它的提示，我应该没有给错 API 接口地址才对。

**Comment by BennyThink** [comment]
试试

https://burn.hair/v1

或者

https://burn.hair/v1/chat/completions

**Comment by wtocch** [comment]
搭车问一下，沉浸翻译的并发值设置多少为好？

**Comment by BennyThink** [comment]
> 搭车问一下，沉浸翻译的并发值设置多少为好？

你可以参考软件作者的建议。

我这边也没有什么并发限制，以3.5为例的话，非流请求你设置成几十都是没问题的。
