### ISSUE TITLE
没有绑定tg按钮?

### ISSUE THREAD

**Issue by sparkssssssss** [BurnHair/issues#72]
![Snipaste_2024-05-07_13-10-23](https://github.com/BurnHair/issues/assets/14211550/cb562240-1288-41a9-897b-53a9c3b361e8)
没有绑定的地方,请指点!

**Comment by vicacheung** [comment]
有的
![image](https://github.com/BurnHair/issues/assets/5325628/df0f480d-19e2-4d81-8f93-1eb132421806)

**Comment by sparkssssssss** [comment]
> 有的 ![image](https://private-user-images.githubusercontent.com/5325628/328395204-df0f480d-19e2-4d81-8f93-1eb132421806.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjQ5MjIsIm5iZiI6MTcxNTA2NDYyMiwicGF0aCI6Ii81MzI1NjI4LzMyODM5NTIwNC1kZjBmNDgwZC0xOWUyLTRkODEtOGY5My0xZWIxMzI0MjE4MDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDY1MDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWZlYTA4MjFmZTZhMDZlMDA2Yzc2MmEzNmM2MzZmZDg5NWYwODlhZjIxMDg1MDM0ZTY0YjQ2NDg2ZTQwY2Q4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D_eoFCuM0O-sXFV0dNOVTr8MAOGJ0O4_UhsinNU4320)

谢谢,不知道为啥我浏览器提示访问js跨域了,加载不出来,
