### ISSUE TITLE
github 登录变成了新账号

### ISSUE THREAD

**Issue by dlzmoe** [BurnHair/issues#74]
之前绑定了tg账号，好像是因为修改过GitHub的username， 识别成了新用户，所有额度都清空了

**Comment by BennyThink** [comment]
对的。给我你的改名前后的证明图片，我可以帮你迁移

**Comment by BennyThink** [comment]
https://github.com/BurnHair/issues/issues/73

或者我可以给你一个页面，可以用用户名密码登录。如果需要这样请发邮件给我。

**Comment by 98zi** [comment]
> #73
> 
> 或者我可以给你一个页面，可以用用户名密码登录。如果需要这样请发邮件给我。

感谢，我需要这个方案
