### ISSUE TITLE
text-embedding 的三个模型报错

### ISSUE THREAD

**Issue by relie2008** [BurnHair/issues#75]
<img width="194" alt="image" src="https://github.com/BurnHair/issues/assets/134369802/33e86d99-63b3-4f3e-8e57-fb2d0df23a4f">
<img width="524" alt="image" src="https://github.com/BurnHair/issues/assets/134369802/2c58f337-3e99-456a-a2f6-3b86bc52d3be">

**Comment by BennyThink** [comment]
<img width="831" alt="image" src="https://github.com/BurnHair/issues/assets/14024832/55600e95-2dc0-4ec3-aca4-78b67edf2f65">

你的请求格式不正确，请参考文档 https://github.com/BurnHair/issues/blob/master/doc.md#16-embeddings
