### ISSUE TITLE
会支持 GPT-4o 吗

### ISSUE THREAD

**Issue by devyujie** [BurnHair/issues#78]

**Comment by bxb100** [comment]
@BennyThink 已经上线了, 而且价格比 4 便宜 50%

<img width="1095" alt="SCR-20240514-csby" src="https://github.com/BurnHair/issues/assets/20685961/1ab228f3-0e04-47c6-8477-85fc7dcb7348">

**Comment by wtocch** [comment]
![1715651121645](https://github.com/BurnHair/issues/assets/163509208/c65dc43f-5c50-4359-a1e8-4740cb924f7d)

**Comment by songyp0505** [comment]
同问 🙋‍♂️

**Comment by farion1231** [comment]
等一个~

**Comment by BennyThink** [comment]
再试试，添加好了，应该没错

**Comment by bxb100** [comment]
> 再试试，添加好了，应该没错

可以用了, 快的一批

**Comment by CNSCSQ** [comment]
> 再试试，添加好了，应该没错

为什么Readme中
{
            "id": "pt-4o-2024-05-13",
            "object": "model",
            "created": 0,
            "owned_by": "system"
}
不是gpt-4o

**Comment by devyujie** [comment]
> > 再试试，添加好了，应该没错
> 
> 为什么Readme中 { "id": "pt-4o-2024-05-13", "object": "model", "created": 0, "owned_by": "system" } 不是gpt-4o

https://github.com/BurnHair/issues/blob/master/README.md?plain=1#L151

**Comment by BennyThink** [comment]
哈哈哈 笔误呗🤣
