### ISSUE TITLE
为什么使用的模型会来回跳呢？

### ISSUE THREAD

**Issue by Micha3ls0n0** [BurnHair/issues#8]
使用的nextchat，选择的 gpt-4-0125-preview
![image](https://github.com/BurnHair/issues/assets/51562299/7f254b1f-cf8f-4cd6-a0bc-14a3559c9ae3)

**Comment by gengjiawen** [comment]
nextchat有个生成title的功能，会默认使用3.5生成title，可以设置里去掉。但最好保留，因为很便宜。

**Comment by gengjiawen** [comment]
> nextchat有个生成title的功能，会默认使用3.5生成title，可以设置里去掉。但最好保留，因为很便宜。

@BennyThink 你加到首页或者QA吧，太多人问了
