### ISSUE TITLE
你好，我的账号被封禁了

### ISSUE THREAD

**Issue by yf283477396** [BurnHair/issues#80]
我并没有重复注册或自己邀请自己，但提示账号被封禁，账号:yf283477396。烦请处理，谢谢

**Comment by BennyThink** [comment]
<img width="1076" alt="image" src="https://github.com/BurnHair/issues/assets/14024832/d3d6eaff-3751-4d10-9b64-e381e9557867">

看起来三个都是一个人 :-(

**Comment by yf283477396** [comment]
您的来信已收到！

**Comment by yf283477396** [comment]
这应该是因为我们公司使用的云浏览器导致的，并不是有意重复注册

**Comment by BennyThink** [comment]
所以你们三个人都是一个公司的吗，那好吧。已经可以了。
