### ISSUE TITLE
支持stream吗

### ISSUE THREAD

**Issue by zluckyhou** [BurnHair/issues#82]
按照openai的文档试了下，调用之后没有正常返回chunk

from openai import OpenAI
client = OpenAI()

completion = client.chat.completions.create(
  model="gpt-4o",
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Hello!"}
  ],
  stream=True
)

for chunk in completion:
  print(chunk.choices[0].delta)

**Comment by BennyThink** [comment]
支持，你要配置 api_key 和 base_url

**Comment by zluckyhou** [comment]
配置了，但是返回的跟openai官网的返回结果不一样呀，有示例代码吗

**Comment by zluckyhou** [comment]
解决了。。。
