### ISSUE TITLE
不支持这些模型

### ISSUE THREAD

**Issue by brotherbear2008** [BurnHair/issues#87]
![image](https://github.com/BurnHair/issues/assets/19421578/da6e392a-b471-48bd-bb85-3923d837aaa2)

**Comment by BennyThink** [comment]
<img width="543" alt="image" src="https://github.com/BurnHair/issues/assets/14024832/de7a9c65-ea49-4905-81d0-95f2a7da0c68">


z支持哦 https://github.com/BurnHair/issues#16-embeddings
