### ISSUE TITLE
为什么我在lobe用4o经常吐字被打断然后undefined

### ISSUE THREAD

**Issue by dao-zero** [BurnHair/issues#88]
如题，刚开始可以正常输出，但是突然一下就变成response.undefined了，已经输出好的也看不了了，在burn日志里面能看到消费记录：
![image](https://github.com/BurnHair/issues/assets/83216969/26924edb-6c5b-4dcc-bff9-a00a3d6e6831)

**Comment by BennyThink** [comment]
我也第一次见，很频繁出现吗？是旧会话，还是新开会话就会有问题？

**Comment by dao-zero** [comment]
是的，很频繁，不对是4o模型只要发消息就会这样，我试了本地部署和其他人的lobe站都是undefined，然后换了一下别人的共享key是不会undefined的，其他模型都没问题

**Comment by chenyangzhu1** [comment]
我在使用GPT academic的时候也遇到了类似的问题
![image](https://github.com/BurnHair/issues/assets/102785092/00499f6f-9170-4b35-9068-e7d332710e6a)

**Comment by BennyThink** [comment]
![image](https://github.com/BurnHair/issues/assets/14024832/4b73cb87-698e-4937-b4da-e5fbc4970449)

很奇怪o哦，我刚刚试了下没问题，也是4o，你的网络到cloudflare连接性如何

**Comment by dao-zero** [comment]
好奇怪，能连，我甚至还能登录，然后其他模型都没问题，只有4o这样

**Comment by dao-zero** [comment]
我换了一个别的接口就可以正常出完文字，但是一样的问题再newchat却又可以吐完，好奇怪

**Comment by deyinliwork** [comment]
尝试关闭语言模型处的“使用客户端请求模式”

**Comment by dao-zero** [comment]
关闭了也还是这样
