### ISSUE TITLE
gpt-4o访问异常

### ISSUE THREAD

**Issue by tianzhuwei** [BurnHair/issues#89]
gpt-3-turbo gpt-4 gpt-4-turbo 均可以正常返回，唯独 gpt-4o 返回以下信息，用其他中转也可正常返回，请帮忙看下是哪里出了问题
![image](https://github.com/BurnHair/issues/assets/16696364/200f6713-8e9e-46ee-8266-56763f0e6d1a)

**Comment by BennyThink** [comment]
可能是偶发的？你再试试呢？我这边一切正常

**Comment by tianzhuwei** [comment]
不是偶尔，是必然复现，我是用于[https://github.com/wibus-wee/raycast-unblock](https://github.com/wibus-wee/raycast-unblock) 这个项目，感觉是返回的字段里面多了或者少了某些东西 不太确定

**Comment by BennyThink** [comment]
哦豁 好的，等有空我也试试这个

**Comment by Moorvan** [comment]
> 不是偶尔，是必然复现，我是用于https://github.com/wibus-wee/raycast-unblock 这个项目，感觉是返回的字段里面多了或者少了某些东西 不太确定 ，抽空我再调试一下代码打印些日志来看

我找到原因了，BurnHair 的 gpt-4o stream 接口（不知道官方是不是也这样），返回的第一个 data 是个空 choices 的结果😂。
<img width="1355" alt="image" src="https://github.com/BurnHair/issues/assets/35735090/a477f9a2-5227-4361-aa27-d26e9ee1667d">
需要修改下 raycast-unblock 中对于这块逻辑的判断就可以正常使用了。

<img width="1457" alt="image" src="https://github.com/BurnHair/issues/assets/35735090/23d9307c-0df3-498b-a2ae-5cc194c5f3dd">

**Comment by BennyThink** [comment]
👍 感谢反馈
