### ISSUE TITLE
无法在dify上调用

### ISSUE THREAD

**Issue by linlinnb123** [BurnHair/issues#95]
使用gpt4o的时候 无法中dify上调用 显示[openai] Error: 'NoneType' object has no attribute 'content' 但是日志中还是会扣费

**Comment by BennyThink** [comment]
猜测和 https://github.com/BurnHair/issues/issues/88 一样。开启了内容审查的话第一个返回的choices 是 []

现在已经修好了，你再试试看呢？

**Comment by linlinnb123** [comment]
还是无法使用gpt4o，会出现消息出现了，但是立马消失的问题，之后网页就提示[openai] Error: 'NoneType' object has no attribute 'content'

**Comment by BennyThink** [comment]
试试升级最新版本， 我看他们修复了

**Comment by BennyThink** [comment]
准备迁移到 GitHub discussions 请在那边重新提issue https://github.com/orgs/BurnHair/discussions
