### ISSUE TITLE
请问每秒最大请求数 最大支持多少

### ISSUE THREAD

**Issue by Astlm** [BurnHair/issues#96]
用3.5设置为5
![Screenshot_2024-06-05-05-08-35-651_com kiwibrowser browser](https://github.com/BurnHair/issues/assets/106404630/edad3193-c27c-4b18-9007-fb228e9b53de)
![Screenshot_2024-06-05-05-08-19-842_com kiwibrowser browser](https://github.com/BurnHair/issues/assets/106404630/2988bb07-2c7f-4b74-b1d2-48b57b2a8d50)
4o更加频繁

**Comment by BennyThink** [comment]
免费用户是每秒5次，付费用户是25.如果需要更高请私聊洽谈。
